
// This file is auto-generated by generate-build-version.js
// Do not edit directly.
export const APP_VERSION = "0.1.0";
export const BUILD_HASH = "78937b1";
export const BUILD_DATE = "12/5/2025 1:51:21 AM";
