
// This file is auto-generated by generate-build-version.js
// Do not edit directly.
export const APP_VERSION = "0.1.0";
export const BUILD_HASH = "aa71f98";
export const BUILD_DATE = "12/6/2025 1:16:04 PM";
